//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsCurrentJob { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EmployerName { get; set; }
        public string EmployerLocation { get; set; }
        public string EmployerState { get; set; }
        public string EmployerCity { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string Accomplishment { get; set; }
        public string Address { get; set; }
    }
}
