//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string OtherName { get; set; }
        public string Surname { get; set; }
        public string email { get; set; }
        public Nullable<int> CurrentSalary { get; set; }
        public string ImagePath { get; set; }
        public string CVPath { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string StateOfOrigin { get; set; }
    }
}
