//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int Id { get; set; }
        public Nullable<long> VacancyId { get; set; }
        public string RequirementDescription { get; set; }
    }
}
