//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string JobRegion { get; set; }
        public string JobLocation { get; set; }
        public string Department { get; set; }
        public string Duration { get; set; }
        public string Level { get; set; }
        public string Description { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string EmploymentType { get; set; }
    }
}
